title: Peter Gehring
description: > # this means to ignore newlines until "baseurl:"
  Ihre Energieberatung mit Herz und Verstand im Rhein-Main-Gebiet.
baseurl: "/petergehring" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Peter Gehring
tagline: Energieberater
about-description: 

- Dipl. Ing. (univ) Maschinenbau, Fachrichtung Energie- und Kraftwerkstechnik
- 2006 Zertifizierung zum Energieberater (HWK) in Würzburg

Nach 35 Jahren in der Industrie (Kraftwerkstechnik, Anlagenbau),bin ich seit 2022 als  Energieberater tätig.
Zu meinem Profil zählen folgende Leistungen

- Vor-Ort-Beratung
- ISFP Individueller Sanierungsfahrplan
- Fördermittelberatung
- Energieausweis
- GEG Nachweis

Eingetragen in der Energie Effizienz-Experten-Liste der Dena (Deutsche Energie-Agentur)
und zugelassen für die Förderprogramme des Bundes
- KfW
- BAFA

pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: p_gehring@web.de # Add your Email address
phone: 0178 317 83 25 # Add your Phone number
website: energieberatung-gehring.de # Add your website, do not add http://
address: |
  Karolingerring 25 
  63791 Karlstein a. M. 
linkedin: # Add your Linkedin handle
#github: artemsheludko # Add your Github handle
#twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
