title: Gehring Peter
description: > # this means to ignore newlines until "baseurl:"
  Ihre Energieberatung mit Herz und Verstand im Rhein-Main-Gebiet.
baseurl: "/petergehring" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: ':title/'
blog_theme: light # Or use dark

# Profile information
name: Gehring Peter
tagline: Energieberater
about-description: Energieberater für Wohngebäude, KfW Haus, Einzelmaßnahme nach BEG, iSFP (individueller Sanierungsfahrplan)
pic: 79.jpg  # Place a 200x200 picture inside /assets/img/ folder and provide the name of the file below

# Contact links
email: p_gehring@web.de # Add your Email address
phone: 06188 7623 # Add your Phone number
website: energieberatung-gehring.de # Add your website, do not add http://
linkedin: # Add your Linkedin handle
#github: artemsheludko # Add your Github handle
#twitter: '@artemsheludko_' # Add your Twitter handle

# Tracker
analytics:

# Comments
discus-identifier: # Add your Disqus identifier

# Important settings
assets:
  sources:
    - assets/fonts
    - assets/img
    - assets/js
    - assets/stylesheets

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

gems:
  - jekyll-feed
  - jekyll-assets
exclude:
  - Gemfile
  - Gemfile.lock

include: [_pages]
